[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fuzzme = "FuzzByLgWcN44Lbfhg91y6XVG2enqieuVZQot7p9mXUp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./keys/FzzrVKHS2VQic1cgvNCbeJJvppcsSF1Zj4D1WbJr45eZ.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
